### PR TITLE
Maths

### PR DESCRIPTION
**Pull request by Slinthn**
I think I have all the stuff to merge this with the master branch!!

### CODE REVIEW

**Comment by DaanSander** [comment]
I believe the rotation matrix is constructed wrong

`Matrix4f Matrix4f::rotation(const Vector3f& axis, fl32 angle) {
			Matrix4f out(1.0f);

			fl32 s = (fl32)sin(degToRad(angle));
			fl32 c = (fl32)cos(degToRad(angle));
			fl32 omc = 1 - c;

			fl32 x = axis.x;
			fl32 y = axis.y;
			fl32 z = axis.z;

			out.mElements[0 + 0 * 4] = c + x * omc;
			out.mElements[1 + 0 * 4] = y * x * omc - z * s;
			out.mElements[2 + 0 * 4] = x * z * omc - y * s;

			out.mElements[0 + 1 * 4] = y * x * omc + z * s;
			out.mElements[1 + 1 * 4] = c + y * omc;
			out.mElements[2 + 1 * 4] = y * z * omc + x * s;

			out.mElements[0 + 2 * 4] = z * x * omc + y * s;
			out.mElements[1 + 2 * 4] = z * y * omc - x * s;
			out.mElements[2 + 2 * 4] = c + z * omc;

			return out;
		}`
This is how I've done it in other engines

**Comment by DaanSander** [comment]
Also you're editing matrices by editing the current one is this your preference?

**Comment by Slinthn** [comment]
Done. Is that all? And yup

**Comment by DaanSander** [comment]
What about 4 dimensional vectors and vector magnitude?

**Pull request merged**
